version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: feedants-mongo
    ports:
      - '27017:27017'
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "try { rs.status().ok } catch { rs.initiate(); }"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2-alpine
    container_name: feedants-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
